### ISSUE TITLE
page-level script that does simple validation

### ISSUE THREAD

**Issue by hchiam** [hchiam/html-template-generator#23]
- [ ] emails should match, but only within each component.  might need to add class names
- [ ] passwords should match, but only within each component.  might need to add class names
- [ ] validate all `input[type="email"]`
- [ ] ~validate all `input[type="number"]`~ --> moved to #26

**Comment by mayuribotre15** [comment]
Hey, @hchiam
Do you want to add validate only for email and password. And perform match operation on email should match and password should match.
If so, then I like to work on it.

**Comment by hchiam** [comment]
Thanks @mayuribotre15 for offering to help! Sure, go ahead with just email and password matching+validation. It turns out [preventing non-number characters from being entered into an `input[type="number"]` by default isn't consistent across browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#:~:text=bear%20in%20mind%20that%2C%20logically%2C%20you%20should%20not%20be%20able%20to%20enter%20characters%20inside%20a%20number%20input%20other%20than%20numbers.%20there%20seems%20to%20be%20some%20disagreement%20about%20this%20among%20browsers), so I'll make a separate issue to investigate/consider that.﻿

**Comment by hchiam** [comment]
@mayuribotre15 let me know if you're still interested in taking this on﻿

**Comment by hchiam** [comment]
just like for #26, validation is kinda out of scope for this html code generator - closing
