### ISSUE TITLE
copy to clipboard

### ISSUE THREAD

**Issue by hchiam** [hchiam/html-template-generator#31]
# Problem/Need:

Copy to clipboard is already included, it's just out of date and not used. It already has the mouse cursor change to indicate it does something different.

# Suggestions:

- [ ] 1) update the version already included in the HTML code: [4.0.0](https://github.com/hchiam/clipboard)
- [ ] 2) use it

**Comment by PushpenderSaini0** [comment]
Hi , i would like to work on this, after updating the version how should i implement the copy feature?
Do i just add a button under `Get output HTML` as `copy to clipboard`

**Comment by hchiam** [comment]
Sorry, that's not quite what I had in mind. Also, I just tested it out and I'll need to use 4.0.1.
